# Generated by Django 2.1.7 on 2019-03-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=32)),
                ('author_email', models.EmailField(max_length=254)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('response_content', models.TextField(max_length=4000)),
            ],
        ),
    ]
