# Generated by Django 2.1.7 on 2019-04-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Konstantin Rebrov', max_length=32)),
                ('article_title', models.CharField(default='', max_length=100)),
                ('article_date', models.DateField(auto_now=True)),
                ('article_link', models.SlugField()),
                ('article_views', models.IntegerField(default='0')),
                ('article_likes', models.IntegerField(default='0')),
            ],
        ),
    ]
