# Generated by Django 2.1.7 on 2019-04-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_article_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='parent_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Article'),
        ),
    ]
