# Generated by Django 2.1.7 on 2019-04-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_response_parent_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['article_date']},
        ),
    ]
