# Generated by Django 2.1.7 on 2019-05-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190509_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='anon_parent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
