# Generated by Django 2.1.7 on 2019-05-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_usercomment_anon_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoncomment',
            options={'ordering': ['comment_date']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['response_date']},
        ),
        migrations.AlterModelOptions(
            name='usercomment',
            options={'ordering': ['comment_date']},
        ),
        migrations.AlterModelOptions(
            name='userresponse',
            options={'ordering': ['response_date']},
        ),
    ]
