# Generated by Django 2.1.7 on 2019-05-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190509_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_type',
            field=models.CharField(default='anon', max_length=4),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response_type',
            field=models.CharField(default='user', max_length=4),
        ),
    ]
