# Generated by Django 2.1.7 on 2019-05-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoncomment',
            name='comment_type',
            field=models.CharField(default='anon', max_length=4),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='comment_type',
            field=models.CharField(default='user', max_length=4),
        ),
    ]
