# Generated by Django 2.1.7 on 2019-05-16 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190509_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=32)),
                ('chat_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=45)),
                ('chat_date', models.DateTimeField(auto_now_add=True)),
                ('chat_content', models.TextField(max_length=4000)),
                ('chat_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ChatInstance')),
            ],
        ),
    ]
