# Generated by Django 2.1.7 on 2019-05-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_chatinstance_chatpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatinstance',
            options={'ordering': ['chat_date']},
        ),
        migrations.AlterModelOptions(
            name='chatpost',
            options={'ordering': ['chat_date']},
        ),
        migrations.AlterField(
            model_name='chatinstance',
            name='chat_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
